<?php

declare(strict_types=1);

use Adl\Controllers\AccountController;
use Adl\Controllers\AdminController;
use Adl\Controllers\AuthController;
use Adl\Controllers\CronController;
use Adl\Controllers\InstallController;
use Adl\Controllers\PageController;
use Adl\Core\Router;

return static function (Router $router): void {
    $router->get('/install', [InstallController::class, 'index']);
    $router->post('/install', [InstallController::class, 'store']);

    $router->get('/sitemap.xml', [PageController::class, 'sitemap']);
    $router->get('/robots.txt', [PageController::class, 'robots']);
    $router->get('/llms.txt', [PageController::class, 'llms']);

    $router->get('/', [PageController::class, 'home']);
    $router->get('/recherche', [PageController::class, 'search']);
    $router->get('/api/recherche', [PageController::class, 'searchApi']);
    $router->get('/cron', [CronController::class, 'index']);
    $router->get('/cron/{task}', [CronController::class, 'run']);
    $router->get('/metiers/{slug}', [PageController::class, 'metier']);
    $router->get('/prestations', [PageController::class, 'prestationsIndex']);
    $router->get('/prestations/{slug}', [PageController::class, 'fiche']);
    $router->get('/prestataires', [PageController::class, 'prestatairesIndex']);
    $router->get('/prestataires/{slug}', [PageController::class, 'profil']);
    $router->get('/missions', [PageController::class, 'missions']);
    $router->get('/missions/{slug}', [PageController::class, 'mission']);
    $router->get('/comment-ca-marche', [PageController::class, 'comment']);
    $router->get('/tarifs', [PageController::class, 'tarifs']);
    $router->get('/confiance', [PageController::class, 'confiance']);
    $router->get('/a-propos', [PageController::class, 'apropos']);
    $router->get('/journal', [PageController::class, 'journal']);
    $router->get('/journal/{slug}', [PageController::class, 'article']);
    $router->get('/aide', [PageController::class, 'aide']);
    $router->get('/mentions-legales', [PageController::class, 'legal']);
    $router->get('/cgu', [PageController::class, 'legal']);
    $router->get('/cgv', [PageController::class, 'legal']);
    $router->get('/confidentialite', [PageController::class, 'legal']);
    $router->get('/cookies', [PageController::class, 'legal']);
    $router->get('/contact', [PageController::class, 'contact']);
    $router->post('/contact', [PageController::class, 'contactSubmit']);

    $router->get('/connexion', [AuthController::class, 'loginForm']);
    $router->post('/connexion', [AuthController::class, 'login']);
    $router->get('/inscription', [AuthController::class, 'registerForm']);
    $router->post('/inscription', [AuthController::class, 'register']);
    $router->get('/inscription/sso', [AuthController::class, 'completeSsoForm']);
    $router->post('/inscription/sso', [AuthController::class, 'completeSso']);
    $router->get('/auth/{provider}', [AuthController::class, 'oauthStart']);
    $router->get('/auth/{provider}/callback', [AuthController::class, 'oauthCallback']);
    $router->post('/deconnexion', [AuthController::class, 'logout']);

    $router->get('/espace', [AccountController::class, 'dashboard']);
    $router->get('/espace/bienvenue', [AccountController::class, 'onboarding']);
    $router->post('/espace/bienvenue', [AccountController::class, 'onboardingSave']);
    $router->get('/espace/publier', [AccountController::class, 'publier']);
    $router->post('/espace/publier', [AccountController::class, 'publierSave']);
    $router->get('/espace/commande', [AccountController::class, 'commande']);
    $router->get('/espace/suivi', [AccountController::class, 'suivi']);
    $router->get('/espace/commandes', [AccountController::class, 'commandes']);
    $router->get('/espace/missions', [AccountController::class, 'missions']);
    $router->get('/espace/candidatures', [AccountController::class, 'candidatures']);
    $router->get('/espace/prestations', [AccountController::class, 'prestations']);
    $router->get('/espace/prestations/creer', [AccountController::class, 'creer']);
    $router->post('/espace/prestations/creer', [AccountController::class, 'creerSave']);
    $router->get('/espace/messages', [AccountController::class, 'messages']);
    $router->get('/espace/notifications', [AccountController::class, 'notifications']);
    $router->post('/espace/notifications/lues', [AccountController::class, 'notificationsRead']);
    $router->get('/espace/notifications/{id}', [AccountController::class, 'notificationOpen']);
    $router->get('/espace/favoris', [AccountController::class, 'favoris']);
    $router->get('/espace/avis', [AccountController::class, 'avis']);
    $router->post('/espace/avis/{id}', [AccountController::class, 'avisSave']);
    $router->get('/espace/vitrine', [AccountController::class, 'vitrine']);
    $router->post('/espace/vitrine', [AccountController::class, 'vitrineSave']);
    $router->post('/espace/disponibilite', [AccountController::class, 'disponibiliteSave']);
    $router->get('/espace/parametres', [AccountController::class, 'parametres']);
    $router->post('/espace/parametres', [AccountController::class, 'parametresSave']);
    $router->get('/espace/facturation', [AccountController::class, 'facturation']);

    $router->get('/admin', [AdminController::class, 'dashboard']);
    $router->get('/admin/verifications', [AdminController::class, 'verifications']);
    $router->post('/admin/verifications/{id}', [AdminController::class, 'verificationSave']);
    $router->get('/admin/moderation', [AdminController::class, 'moderation']);
    $router->post('/admin/moderation/{type}/{id}', [AdminController::class, 'moderationSave']);
    $router->get('/admin/litiges', [AdminController::class, 'litiges']);
    $router->post('/admin/litiges/{id}', [AdminController::class, 'litigeSave']);
    $router->get('/admin/avis', [AdminController::class, 'avis']);
    $router->post('/admin/avis/{id}', [AdminController::class, 'avisSave']);
    $router->get('/admin/utilisateurs', [AdminController::class, 'utilisateurs']);
    $router->get('/admin/utilisateurs/{id}', [AdminController::class, 'utilisateur']);
    $router->post('/admin/utilisateurs/{id}', [AdminController::class, 'utilisateurSave']);
    $router->get('/admin/prestations', [AdminController::class, 'prestations']);
    $router->get('/admin/missions', [AdminController::class, 'missions']);
    $router->get('/admin/finances', [AdminController::class, 'finances']);
    $router->post('/admin/finances/factures/{id}', [AdminController::class, 'invoiceSave']);
    $router->get('/admin/pre-ouverture', [AdminController::class, 'preOuverture']);
    $router->get('/admin/journal', [AdminController::class, 'journal']);
    $router->get('/admin/journal/nouveau', [AdminController::class, 'articleEdit']);
    $router->post('/admin/journal/nouveau', [AdminController::class, 'articleSave']);
    $router->get('/admin/journal/{id}', [AdminController::class, 'articleEdit']);
    $router->post('/admin/journal/{id}', [AdminController::class, 'articleSave']);
    $router->post('/admin/journal/{id}/supprimer', [AdminController::class, 'articleDelete']);
    $router->get('/admin/reglages', [AdminController::class, 'reglages']);
    $router->post('/admin/reglages', [AdminController::class, 'reglagesSave']);
    $router->get('/admin/listes', [AdminController::class, 'listes']);
    $router->post('/admin/listes', [AdminController::class, 'listesSave']);
    $router->get('/admin/smtp', [AdminController::class, 'smtp']);
    $router->post('/admin/smtp', [AdminController::class, 'smtpSave']);
    $router->post('/admin/smtp/test', [AdminController::class, 'smtpTest']);
    $router->get('/admin/sso', [AdminController::class, 'sso']);
    $router->post('/admin/sso', [AdminController::class, 'ssoSave']);
    $router->get('/admin/emails', [AdminController::class, 'emails']);
    $router->get('/admin/emails/{id}', [AdminController::class, 'emailEdit']);
    $router->post('/admin/emails/{id}', [AdminController::class, 'emailSave']);
};
