<?php

declare(strict_types=1);

use Adl\Controllers\AccountController;
use Adl\Controllers\AdminController;
use Adl\Controllers\AuthController;
use Adl\Controllers\CronController;
use Adl\Controllers\InstallController;
use Adl\Controllers\PageController;
use Adl\Core\Router;

return static function (Router $router): void {
    $router->get('/install', [InstallController::class, 'index']);
    $router->post('/install', [InstallController::class, 'store']);

    $router->get('/sitemap.xml', [PageController::class, 'sitemap']);
    $router->get('/robots.txt', [PageController::class, 'robots']);
    $router->get('/llms.txt', [PageController::class, 'llms']);

    $router->get('/', [PageController::class, 'home']);
    $router->get('/recherche', [PageController::class, 'search']);
    $router->get('/api/recherche', [PageController::class, 'searchApi']);
    $router->get('/api/journal', [PageController::class, 'journalApi']);
    $router->get('/cron', [CronController::class, 'index']);
    $router->get('/cron/{task}', [CronController::class, 'run']);
    $router->get('/metiers/{slug}', [PageController::class, 'metier']);
    $router->get('/prestations', [PageController::class, 'prestationsIndex']);
    $router->get('/prestations/{slug}', [PageController::class, 'fiche']);
    $router->get('/prestataires', [PageController::class, 'prestatairesIndex']);
    $router->get('/prestataires/{slug}', [PageController::class, 'profil']);
    $router->get('/missions', [PageController::class, 'missions']);
    $router->get('/missions/{slug}', [PageController::class, 'mission']);
    $router->get('/missions/{slug}/fichier', [PageController::class, 'missionFile']);
    $router->post('/missions/{slug}/candidater', [AccountController::class, 'applicationCreate']);
    $router->get('/comment-ca-marche', [PageController::class, 'comment']);
    $router->get('/tarifs', [PageController::class, 'tarifs']);
    $router->get('/confiance', [PageController::class, 'confiance']);
    $router->get('/a-propos', [PageController::class, 'apropos']);
    $router->get('/journal', [PageController::class, 'journal']);
    $router->get('/journal/{slug}', [PageController::class, 'article']);
    $router->get('/aide', [PageController::class, 'aide']);
    $router->post('/newsletter', [PageController::class, 'newsletter']);
    $router->get('/newsletter/confirmer/{token}', [PageController::class, 'newsletterConfirm']);
    $router->get('/newsletter/desinscription/{token}', [PageController::class, 'newsletterUnsubscribe']);
    $router->post('/newsletter/desinscription/{token}', [PageController::class, 'newsletterUnsubscribe']);
    $router->post('/signaler', [PageController::class, 'report']);
    $router->get('/mentions-legales', [PageController::class, 'legal']);
    $router->get('/cgu', [PageController::class, 'legal']);
    $router->get('/cgv', [PageController::class, 'legal']);
    $router->get('/confidentialite', [PageController::class, 'legal']);
    $router->get('/cookies', [PageController::class, 'legal']);
    $router->get('/regles-ia', [PageController::class, 'legal']);
    $router->get('/contact', [PageController::class, 'contact']);
    $router->post('/contact', [PageController::class, 'contactSubmit']);

    $router->get('/connexion', [AuthController::class, 'loginForm']);
    $router->post('/connexion', [AuthController::class, 'login']);
    $router->get('/mot-de-passe-oublie', [AuthController::class, 'forgotForm']);
    $router->post('/mot-de-passe-oublie', [AuthController::class, 'forgot']);
    $router->get('/mot-de-passe/{token}', [AuthController::class, 'resetForm']);
    $router->post('/mot-de-passe/{token}', [AuthController::class, 'reset']);
    $router->get('/inscription', [AuthController::class, 'registerForm']);
    $router->post('/inscription', [AuthController::class, 'register']);
    $router->get('/inscription/sso', [AuthController::class, 'completeSsoForm']);
    $router->post('/inscription/sso', [AuthController::class, 'completeSso']);
    $router->get('/auth/{provider}', [AuthController::class, 'oauthStart']);
    $router->get('/auth/{provider}/callback', [AuthController::class, 'oauthCallback']);
    $router->post('/deconnexion', [AuthController::class, 'logout']);

    $router->get('/espace', [AccountController::class, 'dashboard']);
    $router->get('/espace/bienvenue', [AccountController::class, 'onboarding']);
    $router->post('/espace/bienvenue', [AccountController::class, 'onboardingSave']);
    $router->get('/espace/publier', [AccountController::class, 'publier']);
    $router->post('/espace/publier', [AccountController::class, 'publierSave']);
    $router->get('/espace/publier/{id}', [AccountController::class, 'publierEdit']);
    $router->post('/espace/publier/{id}', [AccountController::class, 'publierEditSave']);
    $router->post('/espace/publier/{id}/publier', [AccountController::class, 'publierPublish']);
    $router->get('/espace/commande', [AccountController::class, 'commande']);
    $router->post('/espace/commande', [AccountController::class, 'commandeSave']);
    $router->get('/espace/suivi', [AccountController::class, 'suivi']);
    $router->get('/espace/suivi/{id}', [AccountController::class, 'suiviShow']);
    $router->get('/espace/suivi/{id}/depot', [AccountController::class, 'suiviDepotIndex']);
    $router->post('/espace/suivi/{id}/depot', [AccountController::class, 'suiviDepotStore']);
    $router->get('/espace/suivi/{id}/depot/{fid}', [AccountController::class, 'suiviDepotShow']);
    $router->get('/espace/suivi/{id}/depot/{fid}/voir', [AccountController::class, 'suiviDepotView']);
    $router->get('/espace/suivi/{id}/depot/{fid}/telecharger', [AccountController::class, 'suiviDepotDownload']);
    $router->post('/espace/suivi/{id}/depot/{fid}/retirer', [AccountController::class, 'suiviDepotWithdraw']);
    $router->get('/espace/suivi/{id}/fichier/{code}', [AccountController::class, 'suiviFile']);
    $router->post('/espace/suivi/{id}/accepter', [AccountController::class, 'suiviAccept']);
    $router->post('/espace/suivi/{id}/livrer', [AccountController::class, 'suiviDeliver']);
    $router->post('/espace/suivi/{id}/jalon', [AccountController::class, 'suiviJalon']);
    $router->post('/espace/suivi/{id}/devis/refuser', [AccountController::class, 'suiviRefuseQuote']);
    $router->post('/espace/suivi/{id}/annuler', [AccountController::class, 'suiviCancel']);
    $router->post('/espace/suivi/{id}/litige', [AccountController::class, 'suiviDispute']);
    $router->get('/espace/commandes', [AccountController::class, 'commandes']);
    $router->get('/espace/missions', [AccountController::class, 'missions']);
    $router->post('/espace/missions/{id}/supprimer', [AccountController::class, 'missionDelete']);
    $router->get('/espace/candidatures', [AccountController::class, 'candidatures']);
    $router->post('/espace/candidatures/{id}/accepter', [AccountController::class, 'applicationAccept']);
    $router->post('/espace/candidatures/{id}/refuser', [AccountController::class, 'applicationReject']);
    $router->get('/espace/prestations', [AccountController::class, 'prestations']);
    $router->get('/espace/prestations/creer', [AccountController::class, 'creer']);
    $router->post('/espace/prestations/creer', [AccountController::class, 'creerSave']);
    $router->get('/espace/prestations/{id}/modifier', [AccountController::class, 'prestationEdit']);
    $router->post('/espace/prestations/{id}/modifier', [AccountController::class, 'prestationEditSave']);
    $router->post('/espace/prestations/{id}/supprimer', [AccountController::class, 'prestationDelete']);
    $router->get('/espace/messages', [AccountController::class, 'messages']);
    $router->post('/espace/messages', [AccountController::class, 'messages']);
    $router->get('/espace/messages/{id}', [AccountController::class, 'messageShow']);
    $router->get('/espace/messages/{id}/sync', [AccountController::class, 'messageSync']);
    $router->post('/espace/messages/{id}', [AccountController::class, 'messageSend']);
    $router->post('/espace/messages/{id}/signaler', [AccountController::class, 'messageReport']);
    $router->get('/espace/messages/{id}/fichier/{mid}', [AccountController::class, 'messageFile']);
    $router->get('/espace/notifications', [AccountController::class, 'notifications']);
    $router->post('/espace/notifications/lues', [AccountController::class, 'notificationsRead']);
    $router->get('/espace/notifications/{id}', [AccountController::class, 'notificationOpen']);
    $router->get('/espace/favoris', [AccountController::class, 'favoris']);
    $router->post('/espace/favoris/{id}', [AccountController::class, 'favorisToggle']);
    $router->get('/espace/avis', [AccountController::class, 'avis']);
    $router->post('/espace/avis/{id}', [AccountController::class, 'avisSave']);
    $router->get('/espace/vitrine', [AccountController::class, 'vitrine']);
    $router->post('/espace/vitrine', [AccountController::class, 'vitrineSave']);
    $router->post('/espace/vitrine/justificatif', [AccountController::class, 'vitrineVerification']);
    $router->post('/espace/disponibilite', [AccountController::class, 'disponibiliteSave']);
    $router->get('/espace/parametres', [AccountController::class, 'parametres']);
    $router->post('/espace/parametres', [AccountController::class, 'parametresSave']);
    $router->post('/espace/parametres/mot-de-passe', [AccountController::class, 'parametresPassword']);
    $router->post('/espace/parametres/notifications', [AccountController::class, 'parametresNotifs']);
    $router->post('/espace/parametres/facturation', [AccountController::class, 'parametresBilling']);
    $router->post('/espace/parametres/export', [AccountController::class, 'parametresExport']);
    $router->post('/espace/parametres/cloture', [AccountController::class, 'parametresClose']);
    $router->get('/espace/facturation', [AccountController::class, 'facturation']);
    $router->get('/espace/facturation/{id}/pdf', [AccountController::class, 'facturePdf']);

    $router->get('/admin', [AdminController::class, 'dashboard']);
    $router->get('/admin/verifications', [AdminController::class, 'verifications']);
    $router->get('/admin/verifications/{id}/justificatif', [AdminController::class, 'verificationFile']);
    $router->post('/admin/verifications/{id}', [AdminController::class, 'verificationSave']);
    $router->get('/admin/moderation', [AdminController::class, 'moderation']);
    $router->post('/admin/moderation/{type}/{id}', [AdminController::class, 'moderationSave']);
    $router->post('/admin/signalements/{id}', [AdminController::class, 'reportSave']);
    $router->get('/admin/conversations/{id}', [AdminController::class, 'conversationShow']);
    $router->get('/admin/conversations/{id}/fichier/{mid}', [AdminController::class, 'conversationFile']);
    $router->get('/admin/litiges', [AdminController::class, 'litiges']);
    $router->post('/admin/litiges/{id}', [AdminController::class, 'litigeSave']);
    $router->get('/admin/avis', [AdminController::class, 'avis']);
    $router->post('/admin/avis/{id}', [AdminController::class, 'avisSave']);
    $router->get('/admin/utilisateurs', [AdminController::class, 'utilisateurs']);
    $router->get('/admin/utilisateurs/{id}', [AdminController::class, 'utilisateur']);
    $router->post('/admin/utilisateurs/{id}', [AdminController::class, 'utilisateurSave']);
    $router->post('/admin/utilisateurs/{id}/supprimer', [AdminController::class, 'utilisateurDelete']);
    $router->get('/admin/prestations', [AdminController::class, 'prestations']);
    $router->get('/admin/missions', [AdminController::class, 'missions']);
    $router->get('/admin/finances', [AdminController::class, 'finances']);
    $router->post('/admin/finances/factures/{id}', [AdminController::class, 'invoiceSave']);
    $router->get('/admin/pre-ouverture', [AdminController::class, 'preOuverture']);
    $router->get('/admin/journal', [AdminController::class, 'journal']);
    $router->get('/admin/journal/nouveau', [AdminController::class, 'articleEdit']);
    $router->post('/admin/journal/nouveau', [AdminController::class, 'articleSave']);
    $router->get('/admin/journal/{id}', [AdminController::class, 'articleEdit']);
    $router->post('/admin/journal/{id}', [AdminController::class, 'articleSave']);
    $router->post('/admin/journal/{id}/supprimer', [AdminController::class, 'articleDelete']);
    $router->get('/admin/reglages', [AdminController::class, 'reglages']);
    $router->post('/admin/reglages', [AdminController::class, 'reglagesSave']);
    $router->get('/admin/listes', [AdminController::class, 'listes']);
    $router->post('/admin/listes', [AdminController::class, 'listesSave']);
    $router->get('/admin/newsletter', [AdminController::class, 'newsletter']);
    $router->post('/admin/newsletter', [AdminController::class, 'newsletterSave']);
    $router->post('/admin/newsletter/apercu', [AdminController::class, 'newsletterPreview']);
    $router->post('/admin/newsletter/test', [AdminController::class, 'newsletterTest']);
    $router->post('/admin/newsletter/envoyer', [AdminController::class, 'newsletterSend']);
    $router->post('/admin/newsletter/desinscrire', [AdminController::class, 'newsletterUnsub']);
    $router->get('/admin/newsletter/export', [AdminController::class, 'newsletterExport']);
    $router->get('/admin/smtp', [AdminController::class, 'smtp']);
    $router->post('/admin/smtp', [AdminController::class, 'smtpSave']);
    $router->post('/admin/smtp/test', [AdminController::class, 'smtpTest']);
    $router->get('/admin/sso', [AdminController::class, 'sso']);
    $router->post('/admin/sso', [AdminController::class, 'ssoSave']);
    $router->get('/admin/emails', [AdminController::class, 'emails']);
    $router->get('/admin/emails/{id}', [AdminController::class, 'emailEdit']);
    $router->post('/admin/emails/{id}', [AdminController::class, 'emailSave']);
};
